project_id = "cvrqnyibhlcdosyrnrog"

[functions.purchase-coins]
verify_jwt = true

[functions.purchase-mobile-money-coins]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.admin-bulk-import-listings]
verify_jwt = true
